# Generated by Django 5.1.4 on 2024-12-20 19:04

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="M_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("capcity", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "M.2",
            },
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Motherboards",
            },
        ),
        migrations.CreateModel(
            name="Nvme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("capcity", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Nvme",
            },
        ),
        migrations.CreateModel(
            name="Processor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Processors",
            },
        ),
        migrations.CreateModel(
            name="Ram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rams",
            },
        ),
        migrations.CreateModel(
            name="Sdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("capcity", models.CharField(max_length=50)),
                ("product_code", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Sdd",
            },
        ),
        migrations.CreateModel(
            name="Smps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Smps",
            },
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="Hdd",
        ),
        migrations.AlterModelOptions(
            name="hdd",
            options={"verbose_name_plural": "Hdd"},
        ),
        migrations.RenameField(
            model_name="item",
            old_name="category",
            new_name="hdd",
        ),
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
        migrations.RemoveField(
            model_name="item",
            name="expiring_date",
        ),
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="item",
            name="vendor",
        ),
        migrations.AddField(
            model_name="item",
            name="hdd_qty",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="item",
            name="make_and_models",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="motherboard_replacement_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="motherboard_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                    ("replacement", "Replacement"),
                ],
                default="available",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ram_qty",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="item",
            name="serialno",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="item",
            name="smps_replacement_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="smps_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                    ("replacement", "Replacement"),
                ],
                default="available",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ssd_qty",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="item",
            name="motherboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.motherboard",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="processor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.processor",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="ram",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.ram"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="ssd",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.sdd"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="smps",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.smps",
            ),
        ),
    ]
