# Generated by Django 5.1.4 on 2024-12-20 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_m_2_motherboard_nvme_processor_ram_sdd_smps_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="m_2",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nvme",
            options={},
        ),
        migrations.RemoveField(
            model_name="m_2",
            name="capcity",
        ),
        migrations.RemoveField(
            model_name="m_2",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="nvme",
            name="capcity",
        ),
        migrations.RemoveField(
            model_name="nvme",
            name="slug",
        ),
        migrations.AddField(
            model_name="item",
            name="m_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.m_2",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="nvme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.nvme",
            ),
        ),
        migrations.AddField(
            model_name="m_2",
            name="capacity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Capacity in GB",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nvme",
            name="capacity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Capacity in GB",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="m_2",
            name="model",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="m_2",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="m_2",
            name="product_code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="nvme",
            name="model",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="nvme",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="nvme",
            name="product_code",
            field=models.CharField(max_length=255),
        ),
    ]
