# Generated by Django 5.1.4 on 2024-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_m_2_options_alter_nvme_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="m_2",
        ),
        migrations.RemoveField(
            model_name="item",
            name="nvme",
        ),
        migrations.RemoveField(
            model_name="sdd",
            name="capcity",
        ),
        migrations.RemoveField(
            model_name="sdd",
            name="product_code",
        ),
        migrations.AddField(
            model_name="hdd",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hdd",
            name="serial_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="hdd",
            name="unit_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processor",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processor",
            name="serial_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="processor",
            name="unit_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ram",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ram",
            name="serial_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ram",
            name="unit_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sdd",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sdd",
            name="serial_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sdd",
            name="unit_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="hdd_qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram_qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd_qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name="M_2",
        ),
        migrations.DeleteModel(
            name="Nvme",
        ),
    ]
