# Generated by Django 5.1.4 on 2025-01-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_item_hdd_alter_item_motherboard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="processor_qty",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
