# Generated by Django 5.1.4 on 2025-01-17 19:18

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_item_motherboard_remove_item_smps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hdd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="processor",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="serialno",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
