# Generated by Django 5.1.4 on 2025-02-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_item_hdd_alter_item_processor_alter_item_ram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hdd",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="hdd_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="motherboard_replacement_description",
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="processor",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="processor_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="smps_replacement_description",
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd_qty",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
