# Generated by Django 5.1.4 on 2025-03-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_item_hdd_alter_item_hdd_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ram",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rams",
                to="store.item",
            ),
        ),
    ]
