# Generated by Django 5.1.4 on 2025-03-28 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_ram_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="hdd",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hdds",
                to="store.item",
            ),
        ),
        migrations.AddField(
            model_name="processor",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processors",
                to="store.item",
            ),
        ),
        migrations.AddField(
            model_name="sdd",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ssds",
                to="store.item",
            ),
        ),
    ]
