# Generated by Django 5.1.4 on 2025-04-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_hdd_item_processor_item_sdd_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hdd",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="processor",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd",
            field=models.CharField(default="", max_length=50),
        ),
    ]
