# Generated by Django 5.1.4 on 2025-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_item_hdd_alter_item_processor_alter_item_ram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hdd_qty",
            field=models.PositiveIntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="item",
            name="processor_qty",
            field=models.PositiveIntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram_qty",
            field=models.PositiveIntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd_qty",
            field=models.PositiveIntegerField(default=""),
        ),
    ]
