# Generated by Django 5.1.4 on 2025-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_item_hdd_qty_alter_item_processor_qty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="hdd",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="hdd_qty",
            field=models.PositiveIntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="item",
            name="processor_qty",
            field=models.PositiveIntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram_qty",
            field=models.PositiveIntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd_qty",
            field=models.PositiveIntegerField(default="0"),
        ),
    ]
