# Generated by Django 5.1.4 on 2025-04-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_item_hdd_alter_item_hdd_qty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hdd",
            name="item",
        ),
        migrations.RemoveField(
            model_name="processor",
            name="item",
        ),
        migrations.RemoveField(
            model_name="ram",
            name="item",
        ),
        migrations.RemoveField(
            model_name="sdd",
            name="item",
        ),
        migrations.AlterField(
            model_name="item",
            name="hdd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="hdd_qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="processor",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="processor_qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="ram_qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="ssd_qty",
            field=models.PositiveIntegerField(),
        ),
    ]
