# Generated by Django 5.1.4 on 2025-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_remove_hdd_item_remove_processor_item_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sdd",
            new_name="Ssd",
        ),
        migrations.RemoveField(
            model_name="item",
            name="hdd",
        ),
        migrations.RemoveField(
            model_name="item",
            name="hdd_qty",
        ),
        migrations.RemoveField(
            model_name="item",
            name="processor",
        ),
        migrations.RemoveField(
            model_name="item",
            name="processor_qty",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ram",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ram_qty",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ssd",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ssd_qty",
        ),
        migrations.AddField(
            model_name="item",
            name="hdds",
            field=models.ManyToManyField(blank=True, to="store.hdd"),
        ),
        migrations.AddField(
            model_name="item",
            name="processors",
            field=models.ManyToManyField(blank=True, to="store.processor"),
        ),
        migrations.AddField(
            model_name="item",
            name="rams",
            field=models.ManyToManyField(blank=True, to="store.ram"),
        ),
        migrations.AddField(
            model_name="item",
            name="ssds",
            field=models.ManyToManyField(blank=True, to="store.ssd"),
        ),
    ]
