# Generated by Django 5.1.4 on 2025-04-16 05:53

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_rename_sdd_ssd_remove_item_hdd_remove_item_hdd_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catogaryitem",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name"
            ),
        ),
    ]
