# Generated by Django 5.1.4 on 2025-04-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_catogaryitem_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="catogaryitemclone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ssd", "SSD"),
                            ("processor", "Processor"),
                            ("hdd", "HDD"),
                            ("ram", "RAM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial_no", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name_plural": "category_clone",
            },
        ),
        migrations.RemoveField(
            model_name="catogaryitem",
            name="slug",
        ),
    ]
