# Generated by Django 5.1.4 on 2025-04-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_catogaryitemclone_remove_catogaryitem_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="hdds",
        ),
        migrations.RemoveField(
            model_name="item",
            name="processors",
        ),
        migrations.RemoveField(
            model_name="item",
            name="rams",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ssds",
        ),
        migrations.AddField(
            model_name="item",
            name="catogary_item_clone",
            field=models.ManyToManyField(blank=True, to="store.catogaryitemclone"),
        ),
    ]
