# Generated by Django 5.1.4 on 2025-04-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_remove_item_hdds_remove_item_processors_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="catogaryitemclone",
        ),
        migrations.AlterModelOptions(
            name="catogaryitem",
            options={"verbose_name_plural": "category_clone"},
        ),
        migrations.AlterField(
            model_name="item",
            name="catogary_item_clone",
            field=models.ManyToManyField(blank=True, to="store.catogaryitem"),
        ),
    ]
