# Generated by Django 5.1.4 on 2025-04-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_delete_catogaryitemclone_alter_catogaryitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catogaryitem",
            options={"verbose_name_plural": "category_item"},
        ),
    ]
