# Generated by Django 5.1.4 on 2025-05-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_alter_catogaryitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catogaryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ssds", "SSD"),
                    ("processors", "Processor"),
                    ("hdds", "HDD"),
                    ("rams", "RAM"),
                ],
                max_length=20,
            ),
        ),
    ]
