# Generated by Django 5.1.4 on 2025-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_alter_catogaryitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catogaryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ssd", "SSD"),
                    ("processor", "Processor"),
                    ("hdd", "HDD"),
                    ("ram", "RAM"),
                ],
                max_length=20,
            ),
        ),
    ]
