# Generated by Django 5.1.4 on 2025-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_alter_catogaryitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catogaryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ssd", "SSDs"),
                    ("processor", "Processors"),
                    ("hdd", "HDDs"),
                    ("ram", "RAMs"),
                ],
                max_length=20,
            ),
        ),
    ]
