# Generated by Django 5.1.4 on 2025-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_alter_catogaryitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
