# Generated by Django 5.1.4 on 2025-06-11 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_item_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="catogary_item_clone",
        ),
        migrations.AddField(
            model_name="item",
            name="hdd",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "hdd"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hdd_items",
                to="store.catogaryitem",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="processor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "processor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processor_items",
                to="store.catogaryitem",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ram",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "ram"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ram_items",
                to="store.catogaryitem",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ssd",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "ssd"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ssd_items",
                to="store.catogaryitem",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
