# Generated by Django 5.1.4 on 2025-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_remove_item_catogary_item_clone_item_hdd_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="hdd",
        ),
        migrations.RemoveField(
            model_name="item",
            name="processor",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ram",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ssd",
        ),
        migrations.AddField(
            model_name="item",
            name="hdds",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"category": "hdd"},
                related_name="items_as_hdd",
                to="store.catogaryitem",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="processors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"category": "processor"},
                related_name="items_as_processor",
                to="store.catogaryitem",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rams",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"category": "ram"},
                related_name="items_as_ram",
                to="store.catogaryitem",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ssds",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"category": "ssd"},
                related_name="items_as_ssd",
                to="store.catogaryitem",
            ),
        ),
    ]
