# Generated by Django 5.1.4 on 2025-06-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_remove_item_hdd_remove_item_processor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="hdds",
        ),
        migrations.RemoveField(
            model_name="item",
            name="processors",
        ),
        migrations.RemoveField(
            model_name="item",
            name="rams",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ssds",
        ),
        migrations.AddField(
            model_name="item",
            name="catogary_item_clone",
            field=models.ManyToManyField(blank=True, to="store.catogaryitem"),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
