# Generated by Django 5.1.4 on 2025-06-13 09:18

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0031_remove_item_hdds_remove_item_processors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bankaccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                ("acc_name", models.CharField(max_length=50)),
                ("opening_balance", models.CharField(max_length=50, null=True)),
                ("as_of_date", models.DateField()),
            ],
        ),
    ]
