# Generated by Django 5.1.4 on 2025-06-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0032_bankaccount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bankaccount",
        ),
    ]
