# Generated by Django 5.1.4 on 2025-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0033_delete_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="hdds",
            field=models.ManyToManyField(
                blank=True, related_name="items_as_hdds", to="store.catogaryitem"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="processors",
            field=models.ManyToManyField(
                blank=True, related_name="items_as_processors", to="store.catogaryitem"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rams",
            field=models.ManyToManyField(
                blank=True, related_name="items_as_rams", to="store.catogaryitem"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ssds",
            field=models.ManyToManyField(
                blank=True, related_name="items_as_ssds", to="store.catogaryitem"
            ),
        ),
    ]
