# Generated by Django 5.1.4 on 2025-06-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0034_item_hdds_item_processors_item_rams_item_ssds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="hdds",
        ),
        migrations.RemoveField(
            model_name="item",
            name="processors",
        ),
        migrations.RemoveField(
            model_name="item",
            name="rams",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ssds",
        ),
    ]
