# Generated by Django 5.1.4 on 2025-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0037_catogaryitem_updated_by_catogaryitem_updated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catogaryitem",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
