# Generated by Django 5.1.4 on 2025-06-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0038_alter_catogaryitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
