# Generated by Django 5.1.4 on 2025-06-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0039_alter_item_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
