# Generated by Django 5.1.4 on 2025-06-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0040_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
