# Generated by Django 5.1.4 on 2025-06-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0042_item_purchased_code_item_purchased_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="purchased_date",
        ),
        migrations.RemoveField(
            model_name="item",
            name="vendor_price",
        ),
    ]
