# Generated by Django 5.1.4 on 2025-06-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0043_remove_item_purchased_date_remove_item_vendor_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="vendor_name",
        ),
    ]
