# Generated by Django 5.1.4 on 2025-08-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_vendor_gstin"),
        ("store", "0044_remove_item_vendor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                db_column="customer",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.customer",
            ),
        ),
    ]
