# Generated by Django 5.1.4 on 2025-08-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0045_item_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the item",
                max_length=500,
                null=True,
            ),
        ),
    ]
