# Generated by Django 5.1.4 on 2025-08-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0046_item_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="motherboard_status",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                    ("replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="smps_status",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                    ("replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
    ]
