# Generated by Django 5.1.4 on 2025-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0047_alter_item_motherboard_status_alter_item_smps_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="catogaryitem",
            name="purchased_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
