# Generated by Django 5.1.4 on 2025-08-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0049_add_purchased_code_to_catogaryitem"),
    ]

    operations = []
