# Generated by Django 5.1.4 on 2025-08-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0050_rebuild_catogaryitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catogaryitem",
            name="purchased_code",
        ),
    ]
