# Generated by Django 5.1.4 on 2025-08-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0051_remove_catogaryitem_purchased_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="catogaryitem",
            name="purchase_lot_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
