# Generated by Django 5.1.4 on 2025-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0052_catogaryitem_purchase_lot_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="purchased_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
