# Generated by Django 5.1.4 on 2025-10-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0053_item_purchased_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catogaryitem",
            name="purchase_lot_code",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="catogaryitem",
            name="serial_no",
            field=models.CharField(default="Solv-IT", max_length=100),
        ),
        migrations.AlterField(
            model_name="catogaryitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
