# Generated by Django 5.1.4 on 2025-10-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0054_alter_catogaryitem_purchase_lot_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial_no", models.CharField(max_length=100, unique=True)),
                (
                    "make_and_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("processor", models.CharField(blank=True, max_length=100, null=True)),
                ("ram", models.CharField(blank=True, max_length=100, null=True)),
                ("hdd", models.CharField(blank=True, max_length=100, null=True)),
                ("ssd", models.CharField(blank=True, max_length=100, null=True)),
                ("smps", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "motherboard",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
