# Generated by Django 5.1.4 on 2025-10-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0058_operativeupdatelog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OperativeUpdateLog",
        ),
    ]
