# Generated by Django 5.1.4 on 2025-11-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0059_delete_operativeupdatelog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InventoryItem",
        ),
        migrations.AlterField(
            model_name="item",
            name="purchased_type",
            field=models.CharField(
                choices=[("vendor", "Vendor"), ("customer", "Customer")],
                default="NA",
                max_length=50,
            ),
        ),
    ]
