# Generated by Django 5.1.4 on 2025-11-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0060_delete_inventoryitem_alter_item_purchased_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="motherboard_status",
            field=models.CharField(
                choices=[
                    ("Na", "NA"),
                    ("Available", "Available"),
                    ("Not_available", "Not Available"),
                    ("Replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="smps_status",
            field=models.CharField(
                choices=[
                    ("Na", "NA"),
                    ("Available", "Available"),
                    ("Not_available", "Not Available"),
                    ("Replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
    ]
