# Generated by Django 5.1.4 on 2025-12-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0062_alter_item_motherboard_status_alter_item_smps_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="motherboard_status",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("available", "Available"),
                    ("not available", "Not Available"),
                    ("Replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="smps_status",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("available", "Available"),
                    ("not available", "Not Available"),
                    ("Replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
    ]
