# Generated by Django 5.1.4 on 2025-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0063_alter_item_motherboard_status_alter_item_smps_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="motherboard_status",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("Available", "Available"),
                    ("Not available", "Not Available"),
                    ("Replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="purchased_type",
            field=models.CharField(
                choices=[("Vendor", "Vendor"), ("Customer", "Customer")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="smps_status",
            field=models.CharField(
                choices=[
                    ("NA", "NA"),
                    ("Available", "Available"),
                    ("Not available", "Not Available"),
                    ("Replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
    ]
