# Generated by Django 5.1.4 on 2025-12-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0064_alter_item_motherboard_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="motherboard_status",
            field=models.CharField(
                choices=[
                    ("Na", "NA"),
                    ("available", "Available"),
                    ("not available", "Not Available"),
                    ("Replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="purchased_type",
            field=models.CharField(
                choices=[("vendor", "Vendor"), ("customer", "Customer")],
                default="NA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="smps_status",
            field=models.CharField(
                choices=[
                    ("Na", "NA"),
                    ("available", "Available"),
                    ("not available", "Not Available"),
                    ("Replacement", "Replacement"),
                ],
                default="NA",
                max_length=50,
            ),
        ),
    ]
