# Generated by Django 5.1.4 on 2025-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0065_alter_item_motherboard_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="purchased_type",
            field=models.CharField(
                blank=True,
                choices=[("vendor", "Vendor"), ("customer", "Customer")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
