# Generated by Django 5.1.4 on 2025-12-09 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0067_alter_item_motherboard_status_alter_item_smps_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("serial_no", models.CharField(max_length=100)),
                ("make_model", models.CharField(blank=True, max_length=255, null=True)),
                ("processor", models.CharField(blank=True, max_length=255, null=True)),
                ("processor_qty", models.IntegerField(default=0)),
                ("ram", models.CharField(blank=True, max_length=255, null=True)),
                ("ram_qty", models.IntegerField(default=0)),
                ("hdd", models.CharField(blank=True, max_length=255, null=True)),
                ("hdd_qty", models.IntegerField(default=0)),
                ("ssd", models.CharField(blank=True, max_length=255, null=True)),
                ("ssd_qty", models.IntegerField(default=0)),
                ("smps", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "motherboard",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSIGN", "Parts Assigned"),
                            ("REMOVE", "Parts Removed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Audit Trail",
                "verbose_name_plural": "Product Audit Trails",
                "ordering": ["-timestamp"],
            },
        ),
    ]
