# Generated by Django 5.1.4 on 2025-12-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0068_productaudittrail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productaudittrail",
            old_name="make_model",
            new_name="make_and_models",
        ),
    ]
