# Generated by Django 5.1.4 on 2025-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0069_rename_make_model_productaudittrail_make_and_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="productaudittrail",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
