# Generated by Django 5.1.4 on 2025-12-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0070_productaudittrail_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaudittrail",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
