# Generated by Django 5.1.4 on 2026-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0071_alter_productaudittrail_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaudittrail",
            name="hdd_qty",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productaudittrail",
            name="processor_qty",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productaudittrail",
            name="ram_qty",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productaudittrail",
            name="ssd_qty",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
