# Generated by Django 5.1.4 on 2026-01-05 09:32

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0071_alter_productaudittrail_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="catogaryitem",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
