# Generated by Django 5.1.4 on 2026-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0072_alter_productaudittrail_hdd_qty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaudittrail",
            name="hdd_qty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productaudittrail",
            name="processor_qty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productaudittrail",
            name="ram_qty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productaudittrail",
            name="ssd_qty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
