# Generated by Django 5.1.4 on 2026-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0073_alter_productaudittrail_hdd_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="barcode_file",
            field=models.CharField(
                blank=True,
                help_text="Path to the barcode PNG file",
                max_length=255,
                null=True,
            ),
        ),
    ]
