# Generated by Django 5.1.4 on 2026-01-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0073_alter_catogaryitem_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catogaryitem",
            name="slug",
        ),
    ]
