# Generated by Django 5.1.4 on 2025-06-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="loyalty_points",
            new_name="gstin",
        ),
    ]
