# Generated by Django 5.1.4 on 2025-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_loyalty_points_customer_gstin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gstin",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
