# Generated by Django 5.1.4 on 2025-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customer_gstin"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="gstin",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
