# Generated by Django 5.1.4 on 2025-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_vendor_gstin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="person_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("vendor", "Vendor")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
