# Generated by Django 5.1.4 on 2025-06-11 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_remove_item_hdd_remove_item_processor_and_more"),
        ("transactions", "0004_sale_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="item",
            field=models.ForeignKey(
                db_column="item",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.item",
            ),
        ),
    ]
