# Generated by Django 5.1.4 on 2025-06-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_sale_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="item",
        ),
    ]
