# Generated by Django 5.1.4 on 2025-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_sale_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="saledetail",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
