# Generated by Django 5.1.4 on 2025-06-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_saledetail_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="item",
        ),
    ]
