# Generated by Django 5.1.4 on 2025-06-13 09:18

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_remove_sale_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bankaccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                ("account_name", models.CharField(max_length=50)),
                ("opening_balance", models.CharField(max_length=50, null=True)),
                (
                    "as_of_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Created Date"
                    ),
                ),
            ],
        ),
    ]
