# Generated by Django 5.1.4 on 2025-06-13 09:31

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_bankaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="account_name"
            ),
        ),
    ]
