# Generated by Django 5.1.4 on 2025-06-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_alter_bankaccount_opening_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("BANK", "Bank Account"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only applicable if method_type is 'BANK'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.bankaccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.paymentmethod",
            ),
        ),
    ]
