# Generated by Django 5.1.4 on 2025-06-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0012_paymentmethod_sale_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="sale",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_type",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Cheque", "Cheque"), ("Bank", "Bank")],
                default="Cash",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
