# Generated by Django 5.1.4 on 2025-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0014_banktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Unpaid", "Unpaid"),
                    ("Balance", "Balance"),
                ],
                default="Unpaid",
                max_length=10,
            ),
        ),
    ]
