# Generated by Django 5.1.4 on 2025-06-20 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0015_sale_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="delivery_status",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="description",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="item",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="total_value",
        ),
        migrations.AddField(
            model_name="purchase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchase",
            name="make_and_models",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="motherboard_replacement_description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="motherboard_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                    ("replacement", "Replacement"),
                ],
                default="available",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="serialno",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="smps_replacement_description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="smps_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                    ("replacement", "Replacement"),
                ],
                default="available",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="updated_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
