# Generated by Django 5.1.4 on 2025-06-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0041_alter_item_price"),
        ("transactions", "0017_purchasecategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="make_and_models",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="motherboard_replacement_description",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="motherboard_status",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="name",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="serialno",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="smps_replacement_description",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="smps_status",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="purchase",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Delivery Date"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="delivery_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Successful")],
                default="P",
                max_length=1,
                verbose_name="Delivery Status",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.item",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="total_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Price per item (Ksh)",
            ),
        ),
        migrations.DeleteModel(
            name="purchasecategory",
        ),
    ]
