# Generated by Django 5.1.4 on 2025-06-24 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0043_remove_item_purchased_date_remove_item_vendor_price"),
        ("transactions", "0018_remove_purchase_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="purchased_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_purchasedcode",
                to="store.item",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_details",
                to="store.item",
            ),
        ),
    ]
