# Generated by Django 5.1.4 on 2025-06-25 06:55

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0019_purchase_purchased_code_alter_purchase_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="catogaryitempurchased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ssd", "SSDs"),
                            ("processor", "Processors"),
                            ("hdd", "HDDs"),
                            ("ram", "RAMs"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial_no", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(blank=True, default=1, null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "purchased_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_itemspurchased_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_itemspurchased_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "category_itempurchased",
            },
        ),
        migrations.CreateModel(
            name="Itempurchased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("serialno", models.CharField(max_length=50, null=True)),
                ("make_and_models", models.CharField(max_length=100, null=True)),
                (
                    "smps_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                            ("replacement", "Replacement"),
                        ],
                        default="available",
                        max_length=50,
                    ),
                ),
                (
                    "smps_replacement_description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "motherboard_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                            ("replacement", "Replacement"),
                        ],
                        default="available",
                        max_length=50,
                    ),
                ),
                (
                    "motherboard_replacement_description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("quantity", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "vendor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "purchased_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "catogary_item_clone",
                    models.ManyToManyField(
                        blank=True, to="transactions.catogaryitempurchased"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itemspurchased_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itemspurchased_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Itemspurchased",
                "ordering": ["name"],
            },
        ),
    ]
