# Generated by Django 5.1.4 on 2025-06-25 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customer_gstin"),
        ("transactions", "0020_catogaryitempurchased_itempurchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempurchased",
            name="vendor_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases_Item",
                to="accounts.vendor",
            ),
        ),
    ]
