# Generated by Django 5.1.4 on 2025-07-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customer_gstin"),
        ("transactions", "0021_alter_itempurchased_vendor_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={"verbose_name": "Purchase", "verbose_name_plural": "purchases"},
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="delivery_status",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="description",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="item",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="price",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="purchased_code",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="total_value",
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="amount_change",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="purchase",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="purchase",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_acc",
                to="transactions.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Purchase Date"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="purchase",
            name="payment_type",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Cheque", "Cheque"), ("Bank", "Bank")],
                default="Cash",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Unpaid", "Unpaid"),
                    ("Balance", "Balance"),
                ],
                default="Unpaid",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="purchase",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="purchase",
            name="tax_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="vendor",
            field=models.ForeignKey(
                db_column="vendor",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.vendor",
            ),
        ),
        migrations.AlterModelTable(
            name="purchase",
            table="purchases",
        ),
        migrations.CreateModel(
            name="PurchaseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("total_detail", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        db_column="itempurchase",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transactions.itempurchased",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        db_column="purchase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchasedetail_set",
                        to="transactions.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Detail",
                "verbose_name_plural": "Purchase Details",
                "db_table": "purchase_details",
            },
        ),
    ]
