# Generated by Django 5.1.4 on 2025-07-22 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0022_alter_purchase_options_remove_purchase_delivery_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedetail",
            name="purchase",
            field=models.ForeignKey(
                db_column="purchase",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="transactions.purchase",
            ),
        ),
    ]
