# Generated by Django 5.1.4 on 2025-07-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0023_alter_purchasedetail_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedetail",
            name="purchase",
            field=models.ForeignKey(
                db_column="purchase",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchasedetail_set",
                to="transactions.purchase",
            ),
        ),
    ]
