# Generated by Django 5.1.4 on 2025-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0024_alter_purchasedetail_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="saledetail",
            name="sell_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
