# Generated by Django 5.1.4 on 2025-08-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0025_saledetail_sell_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saledetail",
            name="sell_price",
        ),
    ]
