# Generated by Django 5.1.4 on 2025-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0026_remove_saledetail_sell_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="saledetail",
            name="sell_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
