# Generated by Django 5.1.4 on 2025-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0027_saledetail_sell_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
