# Generated by Django 5.1.4 on 2025-09-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0028_sale_discount_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="discount_amount",
            new_name="total_discount_amount",
        ),
        migrations.AddField(
            model_name="saledetail",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="saledetail",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
