# Generated by Django 5.1.4 on 2025-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0029_rename_discount_amount_sale_total_discount_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="actual_total_price_before_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
