# Generated by Django 5.1.4 on 2025-09-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0031_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
