# Generated by Django 5.1.4 on 2025-09-09 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customer_person_type"),
        ("transactions", "0032_expense_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banktransaction",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="banktransaction",
            name="bank_account",
        ),
        migrations.RemoveField(
            model_name="banktransaction",
            name="note",
        ),
        migrations.RemoveField(
            model_name="banktransaction",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="banktransaction",
            name="sale",
        ),
        migrations.RemoveField(
            model_name="banktransaction",
            name="transaction_date",
        ),
        migrations.RemoveField(
            model_name="banktransaction",
            name="transaction_type",
        ),
        migrations.CreateModel(
            name="ServiceBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(help_text="e.g. Laptop, Desktop", max_length=100),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_no", models.CharField(blank=True, max_length=100)),
                ("problem_description", models.TextField()),
                ("service_description", models.TextField()),
                (
                    "service_charge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "parts_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("remarks", models.TextField(blank=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.bankaccount",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.purchase",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.sale",
                    ),
                ),
            ],
        ),
    ]
