# Generated by Django 5.1.4 on 2025-09-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0033_remove_banktransaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.purchase",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.sale",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="transaction_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("credit", "Credit"), ("debit", "Debit")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ServiceBill",
        ),
    ]
