# Generated by Django 5.1.4 on 2025-09-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customer_person_type"),
        ("transactions", "0036_servicebill_servicebillitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebillitem",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="servicebillitem",
            name="name",
        ),
        migrations.AddField(
            model_name="servicebillitem",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_bills",
                to="accounts.customer",
            ),
        ),
        migrations.AddField(
            model_name="servicebillitem",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="servicebillitem",
            name="grand_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="servicebillitem",
            name="item_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="servicebillitem",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="servicebillitem",
            name="total_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicebillitem",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicebillitem",
            name="qty",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="servicebillitem",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicebillitem",
            name="tax_amt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicebillitem",
            name="tax_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="servicebillitem",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.DeleteModel(
            name="ServiceBill",
        ),
    ]
