# Generated by Django 5.1.4 on 2025-09-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0037_remove_servicebillitem_bill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebillitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
