# Generated by Django 5.1.4 on 2025-09-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0038_servicebillitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebillitem",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="servicebillitem",
            name="payment_type",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Cheque", "Cheque"), ("Bank", "Bank")],
                default="Cash",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="servicebillitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Unpaid", "Unpaid"),
                    ("Balance", "Balance"),
                ],
                default="Unpaid",
                max_length=10,
            ),
        ),
    ]
