# Generated by Django 5.1.4 on 2025-09-29 11:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0039_servicebillitem_bank_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebillitem",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=10
            ),
        ),
    ]
