# Generated by Django 5.1.4 on 2025-10-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0041_servicebillitem_amount_change"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebillitem",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="servicebillitem",
            name="total",
        ),
    ]
