# Generated by Django 5.1.4 on 2025-12-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0042_remove_servicebillitem_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_source_type",
                    models.CharField(
                        choices=[
                            ("Sale", "Sale"),
                            ("Purchase", "Purchase"),
                            ("Service", "Service"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="transactions.purchase",
                    ),
                ),
                (
                    "receiving_bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_payments",
                        to="transactions.bankaccount",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="transactions.sale",
                    ),
                ),
                (
                    "servicebill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="transactions.servicebillitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
    ]
