# Generated by Django 5.1.4 on 2025-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0043_paymentrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="payment_mode",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Online", "Online")],
                default="Cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Transaction ID for online payments (UPI, Reference Number, etc.)",
                max_length=255,
                null=True,
            ),
        ),
    ]
