# Generated by Django 5.1.4 on 2025-12-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0044_paymentrecord_payment_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="source_bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Original bank account sending the payment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_payments",
                to="transactions.bankaccount",
            ),
        ),
    ]
