# Generated by Django 5.1.4 on 2026-01-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0045_paymentrecord_source_bank_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="receiving_bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_payments",
                to="transactions.bankaccount",
            ),
        ),
    ]
